"""add pending registration fields to otp_verifications

Revision ID: 059bc506a8f3
Revises: 7288d6520d49
Create Date: 2026-06-25 15:19:04.621795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059bc506a8f3'
down_revision: Union[str, Sequence[str], None] = '7288d6520d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('pending_full_name', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('pending_password_hash', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('pending_account_type', sa.Enum('INDIVIDUAL', 'ORGANIZATION', name='accounttype'), nullable=True))
    op.add_column('otp_verifications', sa.Column('pending_organization_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otp_verifications', 'pending_organization_name')
    op.drop_column('otp_verifications', 'pending_account_type')
    op.drop_column('otp_verifications', 'pending_password_hash')
    op.drop_column('otp_verifications', 'pending_full_name')
    # ### end Alembic commands ###
